# -*- coding: utf-8 -*-
"""Exploring Agent - A BrowserAgent subclass for executing exploration tasks.

Each ExploringAgent instance runs in its own working directory with
independent logs, traces, and video recordings. It executes a TaskGroup
from the plan generated by PlanningAgent.
"""
# flake8: noqa: E501
# pylint: disable=C0301

import os
import json
from typing import Optional

from pydantic import BaseModel, Field

from agentscope.memory import InMemoryMemory
from agentscope.message import Msg
from agentscope.tool import Toolkit
from agentscope._logging import logger

from browser_agent import BrowserAgent
from utils.model_loader import AutoModel, AutoFormatter
from utils.mcp_utils import create_browser_client
from utils.token_tracker import TokenUsageTracker
from utils.logger_utils import setup_session_logger, session_context, get_agent_print_hook
from utils.video_manager import VideoManager


class ExplorationResult(BaseModel):
    """Structured result from an exploring agent's execution."""

    group_id: int = Field(description="The task group ID that was executed")
    group_name: str = Field(description="The task group name")
    success: bool = Field(description="Whether the exploration was successful")
    result: str = Field(
        description="Final result summary from the browser agent",
    )
    subtask_progress_summary: str = Field(
        default="",
        description="Detailed progress summary",
    )


from web.event_bus import EventSink
from web.control_hub import ControlHub, AgentControlGate

async def create_and_run_exploring_agent(
    group_id: int,
    group_name: str,
    prompt: str,
    start_url: str,
    work_dir: str,
    model_config: str = "configs/model_config.json",
    mcp_config: str = "configs/mcp_config.json",
    headless: bool = True,
    record_video: bool = False,
    executable_path: Optional[str] = None,
    max_iters: int = 30,
    event_sink: EventSink | None = None,
    control_hub: ControlHub | None = None,
    run_id: str | None = None,
) -> ExplorationResult:
    """Create and run a single exploring agent for a task group.

    This function sets up an independent browser agent with its own
    working directory, browser instance, and tracking infrastructure.

    Args:
        group_id: The task group ID being executed.
        group_name: Human-readable name for the task group.
        prompt: The natural language prompt describing the tasks to execute.
        start_url: HTTP URL to navigate to (must be http:// served by orchestrator).
        work_dir: Working directory for this subagent's logs/traces/videos.
        model_config: Path to model configuration file.
        mcp_config: Path to MCP configuration file.
        headless: Whether to run browser in headless mode.
        record_video: Whether to record video.
        executable_path: Path to browser executable.
        max_iters: Maximum iterations for the browser agent loop.

    Returns:
        ExplorationResult with the outcome of the exploration.
    """
    # Setup working directory structure
    os.makedirs(work_dir, exist_ok=True)

    # Setup independent tracker with custom session directory
    tracker = TokenUsageTracker(session_dir=work_dir)

    # Setup video manager
    video_manager = VideoManager(work_dir, record_session=record_video)

    # The orchestrator handles local file serving; start_url is always HTTP
    actual_url = start_url

    # Setup session logging
    session_logger = setup_session_logger(
        work_dir,
        tracker.timestamp,
        {
            "component": "exploring_agent",
            "group_id": group_id,
            "group_name": group_name,
            "executable_path": executable_path or "default",
        },
    )

    # Set the logging context for the subagent task
    token = session_context.set(session_logger)
    try:
        # Setup MCP browser client
        browser_client, final_executable_path = create_browser_client(
            headless=headless,
            video_manager=video_manager,
            isolated=True,
            executable_path=executable_path,
            mcp_config_path=mcp_config,
        )

        result = ExplorationResult(
            group_id=group_id,
            group_name=group_name,
            success=False,
            result="Agent did not complete",
        )

        try:
            # Connect browser
            await browser_client.connect()
            toolkit = Toolkit()
            await toolkit.register_mcp_client(browser_client)

            # Mark session start for video
            video_manager.start_session()

            # Load model and formatter
            model = AutoModel.from_config(model_config)
            model = tracker.track_model(model)
            formatter = AutoFormatter.from_config(model_config)

            # Track toolkit
            toolkit = tracker.track_toolkit(toolkit)

            # Create control gate
            agent_id = f"{run_id or 'run'}_agent_{group_id}"
            control_gate = AgentControlGate(control_hub, agent_id)

            # Create browser agent
            agent = BrowserAgent(
                name=f"Explorer-{group_id}",
                model=model,
                formatter=formatter,
                memory=InMemoryMemory(),
                toolkit=toolkit,
                max_iters=max_iters,
                start_url=actual_url,
                token_counter=tracker,
                control_gate=control_gate,
            )

            # Attach video manager
            agent.video_manager = video_manager

            # Register hook for recording prints to session log
            agent.register_instance_hook(
                "post_print",
                "json_log_recorder",
                get_agent_print_hook(session_logger),
            )

            # Register hooks for tracking
            agent_hooks = tracker.get_agent_hooks()
            agent.register_instance_hook(
                "pre_reply",
                "tracker_pre_reply",
                agent_hooks["pre_reply"],
            )
            agent.register_instance_hook(
                "post_reply",
                "tracker_post_reply",
                agent_hooks["post_reply"],
            )

            # Execute the task
            logger.info(
                "[Subagent %d: %s] Starting exploration...",
                group_id,
                group_name,
            )

            msg = Msg("User", prompt, role="user")
            reply = await agent(msg, structured_model=ExplorationResult)

            # Extract result
            if reply.metadata and isinstance(reply.metadata, dict):
                result = ExplorationResult(
                    group_id=group_id,
                    group_name=group_name,
                    success=reply.metadata.get("task_done", False),
                    result=reply.metadata.get(
                        "subtask_progress_summary",
                        str(reply.content),
                    ),
                    subtask_progress_summary=reply.metadata.get(
                        "subtask_progress_summary", "",
                    ),
                )
            else:
                result = ExplorationResult(
                    group_id=group_id,
                    group_name=group_name,
                    success=True,
                    result=str(reply.content) if reply.content else "Completed",
                )

            # Update session log with summary
            session_logger.set_summary(tracker.get_summary_dict())
            tracker.show_summary()

            logger.info(
                "[Subagent %d: %s] Exploration complete. Success: %s",
                group_id,
                group_name,
                result.success,
            )

        except Exception as e:
            logger.error(
                "[Subagent %d: %s] Error: %s",
                group_id,
                group_name,
                e,
            )
            result = ExplorationResult(
                group_id=group_id,
                group_name=group_name,
                success=False,
                result=f"Error during exploration: {e}",
            )

        finally:
            # Cleanup
            try:
                if browser_client:
                    try:
                        import asyncio
                        await asyncio.wait_for(
                            browser_client.call_tool("browser_close", {}),
                            timeout=3.0,
                        )
                    except Exception:
                        pass
                    await browser_client.close()

                video_manager.finalize()
            except Exception as cleanup_error:
                logger.warning(
                    "[Subagent %d] Cleanup error: %s",
                    group_id,
                    cleanup_error,
                )
    finally:
        # Always reset the logging context
        session_context.reset(token)

    # Save result to working directory
    result_path = os.path.join(work_dir, "result.json")
    with open(result_path, "w", encoding="utf-8") as f:
        json.dump(result.model_dump(), f, indent=2, ensure_ascii=False)

    return result
